/*Configuring Firebase options for different platforms, such as web, Android, iOS, and macOS, 
because 
Firebase provides platform-specific configuration settings. 
 (yeh jo file jo krrahi hai -----ing ----- is necessary because )

 for example :  Firebase uses platform-specific authentication tokens to verify the identity of users or devices. 
 These tokens are generated and managed differently on each platform.
 Push notifications are delivered differently on Android and iOS. 
 (FCM) Android, while Apple Push Notification Service (APNs) ios.
  */
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHwbU06CiUqsGzWRivGTKvELc6iv9MK_0',
    appId: '1:302861312270:web:60a2eb86c5220b8663375f',
    messagingSenderId: '302861312270',
    projectId: 'labouronline-1b365',
    authDomain: 'labouronline-1b365.firebaseapp.com',
    databaseURL: 'https://labouronline-1b365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'labouronline-1b365.appspot.com',
    measurementId: 'G-5KB0TYR28F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXmW-LRJLfyHf7KX_7YixLGIrISMOu_dE',
    appId: '1:302861312270:android:3fc1659e39b2083463375f',
    messagingSenderId: '302861312270',
    projectId: 'labouronline-1b365',
    databaseURL: 'https://labouronline-1b365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'labouronline-1b365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_2ogWryajxLsieda7phK_sH61oH-oZ8',
    appId: '1:302861312270:ios:c5e1c0d5b3a506a963375f',
    messagingSenderId: '302861312270',
    projectId: 'labouronline-1b365',
    databaseURL: 'https://labouronline-1b365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'labouronline-1b365.appspot.com',
    androidClientId: '302861312270-5vkhsipfekqb2qfh9ife24a6tcljd1b4.apps.googleusercontent.com',
    iosClientId: '302861312270-dkkev3qgpiiefjmu5i2vdkia2cc3tg42.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaamsay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_2ogWryajxLsieda7phK_sH61oH-oZ8',
    appId: '1:302861312270:ios:1fb329c5cf201d0363375f',
    messagingSenderId: '302861312270',
    projectId: 'labouronline-1b365',
    databaseURL: 'https://labouronline-1b365-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'labouronline-1b365.appspot.com',
    androidClientId: '302861312270-5vkhsipfekqb2qfh9ife24a6tcljd1b4.apps.googleusercontent.com',
    iosClientId: '302861312270-uhgejbliu93mo4c6cji4n3t1fs0o808h.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaamsay.RunnerTests',
  );
}
